### ISSUE TITLE
test suite / release?

### ISSUE THREAD

**Issue by yomimono** [hannesm/duration#1]
I seem to recall some mention being made of a test suite under construction, and required before release.  Can you elaborate on what's necessary there?  I'd like to have `duration` available before merging the int64-using `MCLOCK`/`PCLOCK` and `TIME` API changes for Mirage, and I'm happy to devote some time to writing up test cases if that's helpful.

**Comment by hannesm** [comment]
I've added some range checks a while back, test suite would be great (which shows that `to_x (of_x y)` is the identity for all `x` and `y` (within bounds), and that the result of `of_x` is sensible).
